apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-health-check 
  namespace: qalcom-exam
  labels:
    app: consumer-health-check
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: consumer-health-check
  template:
    metadata:
      labels:
        app: consumer-health-check
    spec:
      containers:
      - image: ttl.sh/python-scripts:1h
        imagePullPolicy: Always
        command: ['python', 'consumer-health-check-service.py']
        name: consumer-health-check
        envFrom:
          - configMapRef:
              name: qalcom-env
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

