apiVersion: v1
kind: Service
metadata:
  name: consumer-health-check-service
  namespace: qualcom-task
spec:
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: consumer-health-check
  type: ClusterIP
