apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
  namespace: qualcom-task
  labels:
    app: health-check-service
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
      - image: ttl.sh/python-scripts:1h
        imagePullPolicy: Always
        command: ['python', 'health_check_service.py']
        name: health-check-service
        envFrom:
          - configMapRef:
              name: qualcom-env
