name: CD

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: python-script:1h

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Build Docker image
        run: docker build -t ttl.sh/${{ env.IMAGE_NAME }}.${{ github.sha }} .

      - name: Push Docker image
        run: docker push ttl.sh/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
